server:
  port: 8888


spring:
  profiles: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
  redis:
    shiro:
      host: 127.0.0.1
      port: 6379
      database: 6
      timeout: 0
      password:

#数据源
  dataSource:
    name: test
    #url: jdbc:mysql://127.0.0.1:3306/boot?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF8
    url: jdbc:oracle:thin:@192.168.0.133:1521:orcl
    username: hap
    password: hap
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    #validationQuery: select 'x'  #MYSQL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙

    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      filters: mergeStat,wall,logback
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 6000
      #validation-query: select 'x' #MYSQL
      validation-query: select 'x' from dual
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath*:/**/*Mapper.xml
  type-aliases-package: com.habi.**.entity
  config-location: classpath:mybatis-config.xml

pagehelper:
    #helperDialect: mysql
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql





